---
- name: Create Ansible User, add to Sudoers and upload Ssh Public Key
  hosts: all
  gather_facts: False
  tasks:
  
    - name: Change Root Password
      user:
        name: root
        state: present
        password: "{{ password_noma | password_hash('sha512') }}"
  
    - name: Create User {{ automated_user }} and Add to Wheel Group
      user:
        name: "{{automated_user}}"
        comment: Ansible Management User
    
    - name: Set includedir in Sudoers File
      lineinfile:
        dest: /etc/sudoers
        line: "#includedir /etc/sudoers.d"
        state: present
        validate: "/usr/sbin/visudo -cf %s"
    
    - name: Add User {{ automated_user }} to Sudoers
      lineinfile:
        path: "/etc/sudoers.d/{{automated_user}}"
        line: '{{automated_user}} ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: '/usr/sbin/visudo -cf %s'
        
    - name: Add {{ automated_user }}'s Public key
      authorized_key:
        user: "{{automated_user}}"
        state: present
        manage_dir: yes
        key: https://gist.githubusercontent.com/mndambuki/af1902b38a17446e11e1125020e2c29d/raw/a5c932d2d5e2ed3afa1699736a87005df70b447a/id_rsa.pub

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: Restart ssh
 
    - name: Allow public Key authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PubkeyAuthentication" line="PubkeyAuthentication yes" state=present
      notify: Restart ssh
 
    - name: Disallow empty password authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitEmptyPasswords" line="PermitEmptyPasswords no" state=present
      notify: Restart ssh
  
    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      systemd: 
        name: sshd
        state: restarted
      
