---
- name: Create 2 Directories
  hosts: all
  tasks:

   - name: Creates directory
     file:
       path: ~/demo_directory_created_through_awx
       state: directory
   - name: Creates directory
     file:
       path: ~/another_demo_directory_created_through_awx
       state: directory
