---
- name: Register Host to RHN
  hosts: all
  become: true
  vars:
    ansible_user: root

  tasks:
  - name: Register host to RHN
    redhat_subscription:
      state: present
      username: "mndambuki"
      password: "!QAZ2wsx"
