---
- name: Day One Playbook
  hosts: all
  tasks:
    - name: Creates Some Directory
      file:
        path: "{{folder_path}}"
        state: directory

    - name: Creating an empty file
      file:
        path: "{{folder_path}}/{{file_path}}"
        state: touch
       
    - name: Creating a file with content
      copy:
        dest: "{{folder_path}}/{{file_path2}}"
        content: |
          line 01
          line 02
          
    - name: Ensure SELinux is set to enforcing mode
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=enforcing
        
    - name: Set includedir in sudoers
      lineinfile:
        dest: /etc/sudoers
        line: "#includedir /etc/sudoers.d"
        state: present
        validate: "/usr/sbin/visudo -cf %s"
    - name: Add user "ansibleuser" to sudo
      lineinfile:
        path: /etc/sudoers.d/ansibleuser
        line: 'ansibleuser ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'
        
        
