---
- name: Create Directories
  hosts: all
  tasks:
    - name: Creates directory
      file:
        path: "{{folder_path}}"
        state: directory

    - name: Creating an empty file
      file:
        path: "{{folder_path}}/{{file_path}}"
        state: touch
       
    - name: Creating a file with content
      copy:
        dest: "{{folder_path}}/{{file_path2}}"
        content: |
          line 01
          line 02
