---
- name: Create Directories
  hosts: all
  tasks:
    - name: Creates directory
      file:
        path: "{{folder_path}}"
        state: directory

    - name: Creating an empty file
      file:
        path: "{{folder_path}}/{{file_path}}"
        state: touch
