---
- name: Change root user password
  hosts: all
  gather_facts: False
  tasks:
  
    - name: Change root password
      user:
        name: root 
        password: "{{ password_noma | password_hash('sha512') }}"
